### ISSUE TITLE
is it still currerntly working?

### ISSUE THREAD

**Issue by t8s1n** [Michaelwmx/zsh-ask#3]
ask ... 

it just sends the question to ASK.com

**Comment by Licheam** [comment]
Can you provide more informations on the problem you encountered? If you set up the enviroment correctly as INSTALL.md said, it should be working just fine.

You can use `which ask` in zsh to check your setups.

If you are using other shell like bash, try  with `source zsh-ask.zsh` instead for a quick setup (not tested).

**Comment by t8s1n** [comment]
which ask gave me "ask: aliased to web_search ask"

i'm assuming I just need to remove the web_search plugin, i'll see what come from that

**Comment by t8s1n** [comment]
its still giving me the same answer, im using zsh, how do i stop it from using the web_search plugin

**Comment by t8s1n** [comment]
i think i've gotten it to work but now i get "[ask -c chat with me](assistant: jq: error (at <stdin>:8): Cannot iterate over null (null))"

**Comment by Licheam** [comment]
For this error, you can refer to #1.

**Comment by t8s1n** [comment]
ah i see, insufficient quota, dang i really wanted to use this

**Comment by AnmolTomer** [comment]
@Licheam my account has sufficient quota to use, still I am getting the following error 

`chatgpt -d how to code merge sort in python
{"role":"system", "content":"You are a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: {knowledge_cutoff} Current date: {current_date}"},  {"role":"user", "content":"how to code merge sort in python"}
assistant: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
jq: error (at <stdin>:8): Cannot iterate over null (null)`

is there anything I am doing wrong?

when I am asking the question on web client of ChatGPT from same account I am getting a response SS attached. Am I missing something here?

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/23466376/259220275-bdb35576-2bd2-468d-a7d0-da8ba36c7abe.png)

**Comment by Licheam** [comment]
@AnmolTomer The web interface differs from the ChatGPT API in terms of pricing. The former is free for usage up to 3.5, while the latter is priced based on the number of tokens used. The API offers a consistently fast and steady user experience. You can find the pricing details at https://openai.com/pricing.
